---
- name: start docker
  systemd:
    state: started
    daemon_reload: yes
    name: docker
    enabled: yes

- name: start containerd
  systemd:
    state: started
    daemon_reload: yes
    name: containerd
    enabled: yes
