---
- name: Check istioctl exists
  stat:
    path: /usr/local/bin/istioctl
  register: istioctl_cmd

- name: Install istioctl
  shell: |
    docker pull istio/istioctl:1.5.2
    docker run -dit --name istioctl --rm --entrypoint /bin/sh istio/istioctl:1.5.2
    docker cp istioctl:/usr/local/bin/istioctl /usr/local/bin/istioctl
    docker rm -f istioctl
  when: not istioctl_cmd.stat.exists
