---
- name: Create envoy config directory
  file:
    path: /etc/envoy
    state: directory

- name: Create envoy log directory
  file:
    path: /var/log/envoy
    state: directory

- name: Install envoy
  yum:
    name: getenvoy-envoy
    state: present

- name: Create envoy config
  template:
    src: envoy.yaml.j2
    dest: /etc/envoy/envoy.yaml

- name:  Create envoy systemd unit file
  template:
    src: envoy.service.j2
    dest: /etc/systemd/system/envoy.service
  notify:
  - restart envoy

- name: Enable and started envoy services
  systemd:
    state: started
    daemon_reload: yes
    name: envoy
    enabled: yes
