---
- name: 发送 kubernetes 二进制文件
  copy:
    src: "{{ item }}"
    dest: "/usr/local/bin/"
    mode: 0755
  with_items:
    - kubectl
    - kube-apiserver
    - kube-proxy
    - kubeadm
    - kubelet
    - kube-controller-manager
    - kube-scheduler

- stat:
    path: /etc/profile.d/kubernetes.sh
  register: complite_result

- name: 设置 kubectl 命令补全
  shell: "{{ item }}"
  with_items:
    - echo "source <(kubectl completion bash)" >> /etc/profile.d/kubernetes.sh
  when: not complite_result.stat.exists 

- name: 创建 kubernets 运行目录
  file:
    path: "{{ item }}"
    owner: root
    group: root
    state: directory
    mode: 0755
  with_items:
    - "{{ cert_dir }}"
    - "{{ manifests_dir }}"

  
- name: 分发证书
  synchronize:
    mode: push
    src: "{{ cert_dir }}/"
    dest: "{{ cert_dir }}/"
    rsync_opts:
    - "--rsh=/bin/ssh -o StrictHostKeyChecking=no -o PasswordAuthentication=no -i /vagrant/files/ssh-keys/id_rsa"
  delegate_to: "{{ groups['ssl'][0] }}"
