---
- name: Disable NetworkManager change resolv.conf
  ini_file:
    path: /etc/NetworkManager/NetworkManager.conf
    state: present
    no_extra_spaces: yes
    section: main
    option: dns
    value: none
    backup: yes
  register: networkmanager_conf

- name: Reload NetworkManager
  systemd:
    state: reloaded
    daemon_reload: yes
    name: NetworkManager
  when: networkmanager_conf.changed

- name: Change resolv.conf
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf

- name: Set timezone to Asia/Shanghai
  timezone:
    name: Asia/Shanghai
