---
- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
  - swap
  - none

- name: Register swap status
  command: /sbin/swapon -s
  register: swapon
  changed_when: no

- name: Disable swap
  command: /sbin/swapoff -a
  when: swapon.stdout
