---
- name: Check kubeconfig bootstrap-kubelet.conf exists
  stat:
    path: "{{ kubernetes_kubeconfig_bootstrap_conf }}"
  register: kubeconfig_kubelet_conf_stat

- name: Create kubeconfig bootstrap-kubelet.conf
  shell: |
    kubectl config set-cluster {{ kubernetes_cluster_name }} \
      --certificate-authority={{ kubernetes_ca_cert }} \
      --embed-certs=true \
      --server={{ kubernetes_apiserver_lb_url }} \
      --kubeconfig={{ kubernetes_kubeconfig_bootstrap_conf }}

    kubectl config set-credentials tls-bootstrap-token-user \
      --token={{ kubernetes_bootstrap_token }} \
      --kubeconfig={{ kubernetes_kubeconfig_bootstrap_conf }}

    kubectl config set-context tls-bootstrap-token-user@{{ kubernetes_cluster_name }} \
      --cluster={{ kubernetes_cluster_name }} \
      --user=tls-bootstrap-token-user \
      --kubeconfig={{ kubernetes_kubeconfig_bootstrap_conf }}

    kubectl config use-context tls-bootstrap-token-user@{{ kubernetes_cluster_name }} \
      --kubeconfig={{ kubernetes_kubeconfig_bootstrap_conf }}
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  when: not kubeconfig_kubelet_conf_stat.stat.exists
