---
- name: Copy kubelet binaries to destination directory
  copy:
    src: "{{ local_bin_dir }}/kubernetes/server/bin/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: 0755
    owner: root
    group: root
  with_items:
  - kubelet

- name: Create kubelet manifests directory
  file:
    path: "{{ kubernetes_manifests_dir }}"
    state: directory

- name: Create kubelet systemd service directory
  file:
    path: "{{ kubelet_systemd_conf_dir }}"
    state: directory

- name: Create kubelet runtime directory
  file:
    path: "{{ kubelet_runtime_dir }}"
    state: directory

- name: Create kubelet flags env file
  template:
    src: kubeadm-flags.env.j2
    dest: "{{ kubelet_flags_env }}"
  notify:
  - restart kubelet

- name: Create kubelet config file
  template:
    src: config.yaml.j2
    dest: "{{ kubelet_config_yaml }}"
  notify:
  - restart kubelet

- name: Create kubelet drop-in 10-admin.conf
  template:
    src: 10-kubeadm.conf.j2
    dest:  "{{ kubelet_systemd_conf_dir }}/10-kubeadm.conf"
  notify:
  - restart kubelet

- name: Check kubeconfig bootstrap-kubelet.conf exists
  stat:
    path: "{{ kubelet_bootstrap_conf }}"
  register: kubeconfig_kubelet_conf_stat

- name: Create kubeconfig bootstrap-kubelet.conf
  shell: |
    kubectl config set-cluster {{ kubernetes_cluster_name }} \
      --certificate-authority={{ kubernetes_ca_cert }} \
      --embed-certs=true \
      --server={{ kubernetes_apiserver_lb_url }} \
      --kubeconfig={{ kubelet_bootstrap_conf }}

    kubectl config set-credentials tls-bootstrap-token-user \
      --token={{ kubernetes_bootstrap_token }} \
      --kubeconfig={{ kubelet_bootstrap_conf }}

    kubectl config set-context tls-bootstrap-token-user@{{ kubernetes_cluster_name }} \
      --cluster={{ kubernetes_cluster_name }} \
      --user=tls-bootstrap-token-user \
      --kubeconfig={{ kubelet_bootstrap_conf }}

    kubectl config use-context tls-bootstrap-token-user@{{ kubernetes_cluster_name }} \
      --kubeconfig={{ kubelet_bootstrap_conf }}
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  when: not kubeconfig_kubelet_conf_stat.stat.exists

- name: Create kubelet service unit file
  template:
    src: kubelet.service.j2
    dest: /etc/systemd/system/kubelet.service
  notify:
  - restart kubelet
