---
- name: Copy kubelet binaries to destination directory
  copy:
    src: "{{ local_bin_dir }}/kubernetes/server/bin/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: 0755
    owner: root
    group: root
  with_items:
  - kubelet

- name: Create kubelet manifests directory
  file:
    path: "{{ kubernetes_manifests_dir }}"
    state: directory

- name: Create kubelet systemd service directory
  file:
    path: "{{ kubelet_systemd_conf_dir }}"
    state: directory

- name: Create kubelet runtime directory
  file:
    path: "{{ kubelet_runtime_dir }}"
    state: directory

- name: Create kubelet flags env file
  template:
    src: kubeadm-flags.env.j2
    dest: "{{ kubelet_flags_env }}"
  notify:
  - restart kubelet

- name: Create kubelet config file
  template:
    src: config.yaml.j2
    dest: "{{ kubelet_config_yaml }}"

- name: Create kubelet drop-in 10-admin.conf
  template:
    src: 10-kubeadm.conf.j2
    dest:  "{{ kubelet_systemd_conf_dir }}/10-kubeadm.conf"
  notify:
  - restart kubelet

- name: Create kubelet service unit file
  template:
    src: kubelet.service.j2
    dest: /etc/systemd/system/kubelet.service
  notify:
  - restart kubelet
