---
- name:  Create etcd systemd unit file
  template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service
  notify:
  - restart etcd

- name: Enable and started etcd service
  systemd:
    name: etcd
    state: started
    enabled: yes
