---
prepare_yum_mirror_host: "mirrors.ustc.edu.cn"
prepare_common_app:
- tcpdump
- bind-utils
- telnet
- bash-completion
- vim
- sysstat
- tree
- nc
- socat
- tcpflow
- strace
- make
- jq
- lsof
- unzip
- iftop
- smem
- gdb
- sysstat
prepare_kernel_modules:
- "ip_vs"
- "ip_vs_rr"
- "ip_vs_wrr"
- "ip_vs_sh"
- "nf_conntrack"
- "br_netfilter"
