---
kubernetes_apiserver_key: "{{ kubernetes_certs_dir }}/apiserver.key"
kubernetes_apiserver_csr: "{{ kubernetes_certs_dir }}/apiserver.csr"
kubernetes_apiserver_cert: "{{ kubernetes_certs_dir }}/apiserver.crt"
kubernetes_apiserver_subj: "/CN=kube-apiserver"
kubernetes_apiserver_kubelet_client_key: "{{ kubernetes_certs_dir }}/apiserver-kubelet-client.key"
kubernetes_apiserver_kubelet_client_csr: "{{ kubernetes_certs_dir }}/apiserver-kubelet-client.csr"
kubernetes_apiserver_kubelet_client_cert: "{{ kubernetes_certs_dir }}/apiserver-kubelet-client.crt"
kubernetes_apiserver_kubelet_client_subj: "/O=system:masters/CN=kube-apiserver-kubelet-client"
kubernetes_front_proxy_ca_key: "{{ kubernetes_certs_dir }}/front-proxy-ca.key"
kubernetes_front_proxy_ca_cert: "{{ kubernetes_certs_dir }}/front-proxy-ca.crt"
kubernetes_front_proxy_client_key: "{{ kubernetes_certs_dir }}/front-proxy-client.key"
kubernetes_front_proxy_client_csr: "{{ kubernetes_certs_dir }}/front-proxy-client.csr"
kubernetes_front_proxy_client_cert: "{{ kubernetes_certs_dir }}/front-proxy-client.crt"
kubernetes_front_proxy_client_subj: "/CN=front-proxy-client"
kubernetes_sa_pub: "{{ kubernetes_certs_dir }}/sa.pub"
kubernetes_sa_key: "{{ kubernetes_certs_dir }}/sa.key"
kubernetes_etcd_apiserver_client_key: "{{ kubernetes_certs_dir }}/apiserver-etcd-client.key"
kubernetes_etcd_apiserver_client_csr: "{{ kubernetes_certs_dir }}/apiserver-etcd-client.csr"
kubernetes_etcd_apiserver_client_cert: "{{ kubernetes_certs_dir }}/apiserver-etcd-client.crt"
kubernetes_etcd_apiserver_client_subj: "/O=system:masters/CN=kube-apiserver-etcd-client"
kubernetes_kubeconfig_admin_key: "{{ kubernetes_certs_dir }}/admin.key"
kubernetes_kubeconfig_admin_csr: "{{ kubernetes_certs_dir }}/admin.csr"
kubernetes_kubeconfig_admin_cert: "{{ kubernetes_certs_dir }}/admin.crt"
kubernetes_kubeconfig_admin_subj: "/O=system:masters/CN=kubernetes-admin"
kubernetes_kubeconfig_kubelet_key: "{{ kubernetes_certs_dir }}/kubelet.key"
kubernetes_kubeconfig_kubelet_csr: "{{ kubernetes_certs_dir }}/kubelet.csr"
kubernetes_kubeconfig_kubelet_cert: "{{ kubernetes_certs_dir }}/kubelet.crt"
kubernetes_kubeconfig_controller_manager_key: "{{ kubernetes_certs_dir }}/controller-manager.key"
kubernetes_kubeconfig_controller_manager_csr: "{{ kubernetes_certs_dir }}/controller-manager.csr"
kubernetes_kubeconfig_controller_manager_cert: "{{ kubernetes_certs_dir }}/controller-manager.crt"
kubernetes_kubeconfig_controller_manager_subj: "/CN=system:kube-controller-manager"
kubernetes_kubeconfig_scheduler_key: "{{ kubernetes_certs_dir }}/scheduler.key"
kubernetes_kubeconfig_scheduler_csr: "{{ kubernetes_certs_dir }}/scheduler.csr"
kubernetes_kubeconfig_scheduler_cert: "{{ kubernetes_certs_dir }}/scheduler.crt"
kubernetes_kubeconfig_scheduler_subj: "/CN=system:kube-scheduler"
kubernetes_kubeconfig_admin_conf: "{{ kubernetes_conf_dir }}/admin.conf"
kubernetes_kubeconfig_kubelet_conf: "{{ kubernetes_conf_dir }}/kubelet.conf"
kubernetes_kubeconfig_controller_manager_conf: "{{ kubernetes_conf_dir }}/controller-manager.conf"
kubernetes_kubeconfig_scheduler_conf: "{{ kubernetes_conf_dir }}/scheduler.conf"
kubernetes_apiserver_logfile: "{{ kubernetes_logs_dir }}/kube-apiserver.log"
kubernetes_controller_manager_logfile: "{{ kubernetes_logs_dir }}/kube-controller-manager.log"
kubernetes_scheduler_logfile: "{{ kubernetes_logs_dir }}/kube-scheduler.log"
kubernetes_bootstrap_secret_groups: "system:bootstrappers:kubeadm:default-node-token"
kubernetes_bootstrap_secret_description: "The default bootstrap token generated by 'kubeadm init'."
