---
- name: Create kubernetes addons dir
  file:
    path: "{{ kubernetes_addons_dir }}"
    state: directory

- name: Create kube-proxy addons yaml
  template:
    src: kube-proxy.yaml.j2
    dest: "{{ kubernetes_addons_dir }}/kube-proxy.yaml"
  register: kube_proxy_addons

- name: Check kube-proxy addons exists
  shell: |
    kubectl get ds -n kube-system kube-proxy
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  delegate_to: "{{ groups['kube_master'][0] }}"
  ignore_errors: yes
  changed_when: False
  register: get_kube_proxy

- name: Apply kube-proxy ds and rbac
  shell: |
    kubectl --kubeconfig={{ kubernetes_kubeconfig_admin_conf }} \
    apply -f {{ kubernetes_addons_dir }}/kube-proxy.yaml
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  delegate_to: "{{ groups['kube_master'][0] }}"
  run_once: yes
  when: kube_proxy_addons.changed or 'not found' in get_kube_proxy.stderr

- name: Create coredns addons yaml
  template:
    src: coredns.yaml.j2
    dest: "{{ kubernetes_addons_dir }}/coredns.yaml"
  register: coredns_addons

- name: Check coredns addons exists
  shell: |
    kubectl get deploy -n kube-system coredns
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  delegate_to: "{{ groups['kube_master'][0] }}"
  ignore_errors: yes
  changed_when: False
  register: get_coredns 

- name: Apply coredns deployment and rbac
  shell: |
    kubectl --kubeconfig={{ kubernetes_kubeconfig_admin_conf }} \
    apply -f {{ kubernetes_addons_dir }}/coredns.yaml
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  delegate_to: "{{ groups['kube_master'][0] }}"
  run_once: yes
  when: coredns_addons.changed or 'not found' in get_coredns.stderr

- name: Update bashrc
  template:
    src: bashrc.j2
    dest: "{{ ansible_env.HOME }}/.bashrc"
