---
- name: Create kubernetes addons dir
  file:
    path: "{{ kubernetes_addons_dir }}"
    state: directory

- name: Create kube-proxy addons yaml
  template:
    src: kube-proxy.yaml.j2
    dest: "{{ kubernetes_addons_dir }}/kube-proxy.yaml"
  register: kube_proxy_addons

- name: Apply kube-proxy ds and rbac
  shell: |
    kubectl --kubeconfig={{ kubernetes_kubeconfig_admin_conf }} \
    apply -f {{ kubernetes_addons_dir }}/kube-proxy.yaml
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  delegate_to: "{{ groups['kube_master'][0] }}"
  run_once: yes
  when: kube_proxy_addons.changed

- name: Create coredns addons yaml
  template:
    src: coredns.yaml.j2
    dest: "{{ kubernetes_addons_dir }}/coredns.yaml"
  register: coredns_addons

- name: Apply coredns deployment and rbac
  shell: |
    kubectl --kubeconfig={{ kubernetes_kubeconfig_admin_conf }} \
    apply -f {{ kubernetes_addons_dir }}/coredns.yaml
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  delegate_to: "{{ groups['kube_master'][0] }}"
  run_once: yes
  when: coredns_addons.changed

- name: Update bashrc
  template:
    src: bashrc.j2
    dest: "{{ ansible_env.HOME }}/.bashrc"
