---
- name: Create kubernetes addons dir
  file:
    path: "{{ kubernetes_addons_dir }}"
    state: directory

- name: Create kube-proxy addons yaml
  template:
    src: kube-proxy.yaml.j2
    dest: "{{ kubernetes_addons_dir }}/kube-proxy.yaml"
  register: kube_proxy_addons

- name: Apply kube-proxy ds and rbac
  shell: |
    kubectl --kubeconfig={{ kubernetes_kubeconfig_admin_conf }} \
    apply -f {{ kubernetes_addons_dir }}/kube-proxy.yaml
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  delegate_to: "{{ groups['kube_master'][0] }}"
  run_once: yes
  when: kube_proxy_addons.changed

- name: Create coredns addons yaml
  template:
    src: coredns.yaml.j2
    dest: "{{ kubernetes_addons_dir }}/coredns.yaml"
  register: coredns_addons

- name: Apply coredns deployment and rbac
  shell: |
    kubectl --kubeconfig={{ kubernetes_kubeconfig_admin_conf }} \
    apply -f {{ kubernetes_addons_dir }}/coredns.yaml
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  delegate_to: "{{ groups['kube_master'][0] }}"
  run_once: yes
  when: coredns_addons.changed

- name: Create calico addons yaml
  template:
    src: calico.yaml.j2
    dest: "{{ kubernetes_addons_dir }}/calico.yaml"
  register: calico_addons

- name: Apply calico deployment and rbac
  shell: |
    kubectl --kubeconfig={{ kubernetes_kubeconfig_admin_conf }} \
    apply -f {{ kubernetes_addons_dir }}/calico.yaml
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  delegate_to: "{{ groups['kube_master'][0] }}"
  run_once: yes
  when: calico_addons.changed

- name: Check calicoctl command exists
  stat:
    path: /usr/local/bin/calicoctl
  register: calicoctl_cmd

- name: install calicoctl command
  shell: |
    docker pull calico/ctl:v3.12.0
    docker run -dit --name calicoctl --rm --entrypoint /bin/sh calico/ctl:v3.12.0
    docker cp calicoctl:/calicoctl /usr/local/bin/calicoctl
    docker rm -f calicoctl
  when: not  calicoctl_cmd.stat.exists

- name: Update bashrc
  template:
    src: bashrc.j2
    dest: "{{ ansible_env.HOME }}/.bashrc"
