---
- hosts: all
  become: yes
  roles:
  - prepare

- hosts: all
  become: yes
  roles:
  - runtimes

- hosts: etcd
  become: yes
  pre_tasks:
  - name: Change default ipv4 address using {{ vagrant_network_interface }}
    set_default_route:
      interface: "{{ vagrant_network_interface }}"
      add: yes
    when: is_vagrant | bool
  - name: Gather facts from ALL hosts (regardless of limit or tags)
    setup:
      gather_subset: '!all,!any,network'
    delegate_to: "{{ item }}"
    delegate_facts: yes
    with_items: "{{ groups['etcd'] }}"
  - name: Set ansible_host_ip variables
    set_fact:
      ansible_host_ip: "{{ ansible_default_ipv4.address }}"
  roles:
  - openssl
  - etcd

- hosts: kube_master
  become: yes
  pre_tasks:
  - name: Change default ipv4 address using {{ vagrant_network_interface }}
    set_default_route:
      interface: "{{ vagrant_network_interface }}"
      add: yes
    when: is_vagrant | bool
  - name: Gather facts from ALL hosts (regardless of limit or tags)
    setup:
      gather_subset: '!all,!any,network'
    delegate_to: "{{ item }}"
    delegate_facts: yes
    with_items: "{{ groups['kube_master'] }}"
  - name: Set ansible_host_ip variables
    set_fact:
      ansible_host_ip: "{{ ansible_default_ipv4.address }}"
  roles:
  - openssl
  - loadbalancer
  - kubernetes/master
  - kubernetes/kubelet

- hosts: kube_worker
  become: yes
  pre_tasks:
  - name: Change default ipv4 address using {{ vagrant_network_interface }}
    set_default_route:
      interface: "{{ vagrant_network_interface }}"
      add: yes
    when: is_vagrant | bool
  - name: Gather facts from ALL hosts (regardless of limit or tags)
    setup:
      gather_subset: '!all,!any,network'
    delegate_to: "{{ item }}"
    delegate_facts: yes
    with_items: "{{ groups['kube_master'] }}"
  - name: Set ansible_host_ip variables
    set_fact:
      ansible_host_ip: "{{ ansible_default_ipv4.address }}"
  roles:
  - loadbalancer
  - kubernetes/worker
  - kubernetes/kubelet

- hosts: kube_master
  become: yes
  roles:
  - addons

- hosts: all
  become: yes
  roles:
  - calico
